services:
  mysql:
    image: mysql:8.0.0
    volumes:
      - customers-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: customers
    ports:
      - 3306:3306

volumes:
  customers-mysql-data: